
    drop table if exists Application cascade;

    drop table if exists Invitation cascade;


    drop table if exists PROGRAM_ADMIN cascade;


    drop table if exists Program_list cascade;


    drop table if exists programs cascade;


    drop table if exists programs_Application cascade;


    drop table if exists programs_users cascade;


    drop table if exists user_role cascade;


    drop table if exists users cascade;


    create table Application (
       apiKey uuid not null,
        URL varchar(255) not null,
        description varchar(255),
        invitationURL varchar(255) not null,
        name varchar(255) not null,
        primary key (apiKey)
    );


    create table Invitation (
       id bigint generated by default as identity (start with 1),
        activated timestamp,
        city varchar(255),
        ipAddress varchar(255),
        latitude varchar(255),
        longitude varchar(255),
        byUserId bigint not null,
        declined boolean not null,
        invitationsLeft integer not null,
        programId bigint not null,
        sent timestamp,
        toUserId bigint not null,
        primary key (id)
    );


    create table PROGRAM_ADMIN (
       PROGRAMS_ID bigint not null,
        ADMIN_ID bigint not null,
        primary key (PROGRAMS_ID, ADMIN_ID)
    );


    create table Program_list (
       Program_id bigint not null,
        list varchar(255)
    );


    create table programs (
       id bigint generated by default as identity (start with 1),
        name varchar(255) not null,
        primary key (id)
    );


    create table programs_Application (
       Program_id bigint not null,
        activeApplications_apiKey uuid not null,
        primary key (Program_id, activeApplications_apiKey)
    );


    create table programs_users (
       Program_id bigint not null,
        activeCustomers_id bigint not null,
        primary key (Program_id, activeCustomers_id)
    );

    create table users (
       type varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        created_at timestamp,
        email varchar(70) not null,
        name varchar(40) not null,
        passwd varchar(255) not null,
        primary key (id)
    );

    create table user_role (
	  user_id bigint not null,
	  role varchar(30) not null,
	  primary key(user_id, role),
	  constraint fk_user_roles_user foreign key(user_id) references users(id)
    );

    alter table Application
       add constraint UK_aodndelwf11g1hjqcvxm8jgqo unique (URL);


    alter table Application
       add constraint UK_pf5rxc9stusr5eqxvbdpho9d9 unique (invitationURL);


    alter table programs
       add constraint UK_4uh20rvftatfys82a9nkvpl0o unique (name);


    alter table programs_Application
       add constraint UK_1ye26vq1vsq92v7tij8pfbyjy unique (activeApplications_apiKey);


    alter table users
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);


    alter table PROGRAM_ADMIN
       add constraint FK4ww385skmla2axevunsdahck7
       foreign key (ADMIN_ID)
       references users;


    alter table PROGRAM_ADMIN
       add constraint FKs9s84wfwcjqya3ug5y09tav7o
       foreign key (PROGRAMS_ID)
       references programs;


    alter table Program_list
       add constraint FKitefbocd0a5ra6u60jtw3xe2a
       foreign key (Program_id)
       references programs;


    alter table programs_Application
       add constraint FKh75rxbhguvnmya7iws3imxyxv
       foreign key (activeApplications_apiKey)
       references Application;


    alter table programs_Application
       add constraint FK2n1fn9a1j4x8o28i9dwwfru01
       foreign key (Program_id)
       references programs;


    alter table programs_users
       add constraint FKmqp4rott8ic1ys5eyakx6jxsh
       foreign key (activeCustomers_id)
       references users;


    alter table programs_users
       add constraint FKfhbpgcgin6fmml357fvqifa27
       foreign key (Program_id)
       references programs;

    --Password 123456
    insert into users (created_at, name, email, passwd, type) values(current_timestamp, 'Admin', 'adm@domain.com', 'jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=', 'EMPLOYEE');
    insert into user_role (user_id, role) values((select id from users where email = 'adm@domain.com'), 'EMPLOYEE');
    insert into user_role (user_id, role) values((select id from users where email = 'adm@domain.com'), 'ADMINISTRATOR');

